version: '3.8'

services:
  http_probe:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: http_probe
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env